/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    AboutModal: typeof import('./components/AboutModal.vue')['default']
    AConfigProvider: typeof import('@arco-design/web-vue')['ConfigProvider']
    ASpace: typeof import('@arco-design/web-vue')['Space']
    ATypographyText: typeof import('@arco-design/web-vue')['TypographyText']
    IconBtn: typeof import('./components/IconBtn.vue')['default']
    Logo: typeof import('./components/Logo.vue')['default']
    Modal: typeof import('./components/Modal.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SourceBar: typeof import('./components/SourceBar.vue')['default']
    SourceStreamsData: typeof import('./components/SourceStreamsData.vue')['default']
    Titlebar: typeof import('./components/Titlebar.vue')['default']
    ToolBar: typeof import('./components/ToolBar.vue')['default']
    ToolBtn: typeof import('./components/ToolBtn.vue')['default']
  }
}
